services:
  app:
    build:
      context: .
      dockerfile: etc/docker/fpm/Dockerfile
    working_dir: /app
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: etc/docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8088:80"
    volumes:
      - .:/app:ro
