[global]
pid = /usr/local/var/run/php-fpm.pid
error_log = /tmp/project-yii-fpm-error.log

[www]
listen = 9000
pm = ondemand
pm.max_children = 6
pm.process_idle_timeout = 10s
pm.max_requests = 500
request_terminate_timeout = 60s
catch_workers_output = yes
decorate_workers_output = no
clear_env = no
